### PR TITLE
Add zinit installation method to README.md

### PR DESCRIPTION
**Pull request by bgshacklett**

### CODE REVIEW

**Comment by ckp95** [comment]
Not opposed to including this, but I can see a problem. It looks like you're linking directly to a file from a specific commit, rather than the latest version on master:

```
zinit snippet 'https://raw.githubusercontent.com/ckp95/fwf/6a8cec7a401fdb1928648ac4a68077438392243f/_fwf_main'
```

That URL matches the identifier of the latest commit, `6a8cec7a401fdb1928648ac4a68077438392243f`. So if the repository is updated, zinit will still load the older version.

I haven't used zinit before. Is there a way to make it always use the latest version on the master branch?

**Comment by ckp95** [comment]
By the way, how did you come across this project?

**Comment by bgshacklett** [comment]
So, the reason I linked to a specific commit is that it give some level of protection should the account become compromised. Pulling executable code directly from a URL and putting it in your PATH can be a bit dangerous. Git SHAs are immutable, so given that that URL is currently trustworthy, then it should be trustworthy forever.

I'm certain that there are better ways of doing it. I just don't know what they would be, off the top of my head. Although, if you were to begin cutting releases, I believe there's a checksum which gets generated with the automatically generated archive.

As for how I found the project, it was a bout of frustration with JQ that lead me to google "interactive jq query" or something similar. :-)

**Comment by ckp95** [comment]
Fair enough. Glad to see people using this!

**Pull request merged**
